### ISSUE TITLE
Wrong counter

### ISSUE THREAD

**Issue by tsvetkovv** [nikolay-borzov/react-mentoring#15]
**Steps**: search 'deadpool'

**Actual result:** 2 movies found (15 shown)
![image](https://user-images.githubusercontent.com/11594423/40279368-81d268e6-5c52-11e8-853f-458550ced400.png)

**Expected result:** 2 movies found (2 shown)

**Comment by nikolay-borzov** [comment]
I think `x shown` should be displayed only when found count is bigger than the `limit` parameter value
